### ISSUE TITLE
FF stop Working. "Downloading Bypass Definitions" loop

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [FastForwardTeam/FastForward#999]
### Body

Like the title, Fast forward stops working completely on fresh installs, _you can access the extension settings, however it does not perform any function both on edge and Chrome._ **stays in a "Downloading definitions" loop**

despite numerical version differences between platform; both are First Time installs were run at the same time and day, with the available versions of .zip for chrome and MS Store for edge.

Issue could also be present in Firefox https://github.com/FastForwardTeam/FastForward/issues/998

Additional Info:
Chrome Version 113.0.5672.127 (Official Build) (64-bit) 
 _[Running AdBlock in parallel   but it doesn't seem to be a problem of additional extensions]_
Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit)
OS: Windows 11 Pro 22H2 Build 22621.1702

### Version

0.2251 , 0.2256

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/64709446/a3fd8a82-7049-442f-b6c2-0d611d05faf0)
![image](https://github.com/FastForwardTeam/FastForward/assets/64709446/b450c562-d0f1-4d75-a8c6-c6a3c2188bfd)

**Comment by K-mikaZ** [comment]
seems failes to load resources from background.js (net::ERR_FILE_NOT_FOUND).
> .../src/js/injection_script.js
> .../src/js/rules.json
> .../src/linkvertise.js (firefox only)

`xhr.open("GET", "https://cdn.jsdelivr.net/gh/FastForwardTeam/FastForward@" + upstreamCommit + "/src/js/injection_script.js", true)`

~~A question: instead of "upstreamCommit" variable why do not use "latest"?~~
~~`https://cdn.jsdelivr.net/gh/FastForwardTeam/FastForward@latest/src/js/injection_script.js`~~

**Comment by ghost** [comment]
This is a known issue that occurs when you already have the latest version. We have fixed this in our prerelease MV3 version.

**Comment by UwU990099** [comment]
I have the latest version and it's still happening. It worked a few days ago but not anymore after I accidentally reinstalled the extension. This is on Chrome browser.

update: reinstalled a bunch of times and it finally worked. So weird.
